// build.rs — generate one #[test] fn per .rs file in tests/suite/.
//
// The generated file is written to $OUT_DIR/suite_tests.rs and included by
// tests/run_tests.rs. This gives cargo test a separate, parallel test entry
// point for every source file in the suite directory.

use std::{env, fs, path::PathBuf};

fn main() {
    let suite = "tests/suite";
    println!("cargo:rerun-if-changed={suite}");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let out_path = out_dir.join("suite_tests.rs");

    let mut entries: Vec<_> = fs::read_dir(suite)
        .expect("tests/suite not found")
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().map_or(false, |x| x == "rs"))
        .collect();
    entries.sort_by_key(|e| e.file_name());

    let mut code = String::from("// Auto-generated by build.rs -- do not edit.\n");

    for entry in &entries {
        let path = entry.path();
        // Emit rerun directive so a changed test file triggers regeneration.
        println!("cargo:rerun-if-changed={}", path.display());

        let stem = path.file_stem().unwrap().to_string_lossy();
        // Turn the file stem into a valid Rust identifier: digits-first stems
        // get a `t_` prefix, other non-alphanumeric chars become `_`.
        let fn_name = {
            let sanitized: String = stem
                .chars()
                .map(|c| if c.is_alphanumeric() { c } else { '_' })
                .collect();
            if sanitized
                .chars()
                .next()
                .map_or(true, |c| c.is_ascii_digit())
            {
                format!("t_{sanitized}")
            } else {
                sanitized
            }
        };

        code.push_str(&format!(
            "\n#[test]\nfn {fn_name}() {{\n    run_test(\"{}\");\n}}\n",
            path.display()
        ));
    }

    fs::write(&out_path, code).expect("failed to write suite_tests.rs");
}
