// build.rs — generate one #[test] fn per .rs file in tests/suite/ and
// tests/suite/errors/.
//
// The generated file is written to $OUT_DIR/suite_tests.rs and included by
// tests/run_tests.rs. This gives cargo test a separate, parallel test entry
// point for every source file in both suite directories.

use std::{env, fs, path::PathBuf};

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let out_path = out_dir.join("suite_tests.rs");

    let mut code = String::from("// Auto-generated by build.rs -- do not edit.\n");

    for suite in &["tests/suite", "tests/suite/errors"] {
        println!("cargo:rerun-if-changed={suite}");

        let Ok(read_dir) = fs::read_dir(suite) else {
            continue;
        };
        let mut entries: Vec<_> = read_dir
            .filter_map(|e| e.ok())
            .filter(|e| e.path().extension().map_or(false, |x| x == "rs"))
            .collect();
        entries.sort_by_key(|e| e.file_name());

        for entry in &entries {
            let path = entry.path();
            println!("cargo:rerun-if-changed={}", path.display());

            let stem = path.file_stem().unwrap().to_string_lossy();
            // Build a valid Rust identifier from the stem. Digits-first stems
            // get a `t_` prefix; other non-alphanumeric chars become `_`.
            let sanitized: String = stem
                .chars()
                .map(|c| if c.is_alphanumeric() { c } else { '_' })
                .collect();
            let fn_name = if sanitized.chars().next().map_or(true, |c| c.is_ascii_digit()) {
                format!("t_{sanitized}")
            } else {
                sanitized
            };

            code.push_str(&format!(
                "\n#[test]\nfn {fn_name}() {{\n    run_test(\"{}\");\n}}\n",
                path.display()
            ));
        }
    }

    fs::write(&out_path, code).expect("failed to write suite_tests.rs");
}
