//! Integration tests for the brust compiler.
//!
//! Two kinds of test files live under `tests/suite/`:
//!
//! - **Success tests** (`tests/suite/*.rs`): compiled to a binary and run;
//!   stdout must match `// out: <line>` comments at the top of the file.
//!
//! - **Error tests** (`tests/suite/errors/*.rs`): brust must exit non-zero
//!   and its stderr must contain every `// err: <substring>` listed at the
//!   top of the file.
//!
//! Each test file gets its own `#[test]` function (generated by build.rs), so
//! cargo runs them all in parallel and reports failures individually.

use std::{fs, path::Path, process::Command};

// Resolved at compile time by cargo.
const BRUST: &str = env!("CARGO_BIN_EXE_brust");

/// Parsed expectations from a test file header.
enum Expect {
    /// Compile + run; stdout must equal these lines.
    Success(Vec<String>),
    /// Compile must fail; stderr must contain all these substrings.
    Error(Vec<String>),
}

/// Run a single test file. Behaviour depends on the header comments:
/// - `// out: <line>` → success test
/// - `// err: <substring>` → error test (compilation must fail)
fn run_test(path_str: &str) {
    let path = Path::new(path_str);
    let src = fs::read_to_string(path).unwrap_or_else(|e| panic!("cannot read {path_str}: {e}"));
    let expect = parse_header(&src);

    let tmp = std::env::temp_dir().join("brust_test_suite");
    fs::create_dir_all(&tmp).expect("cannot create temp dir");
    let stem = path.file_stem().unwrap().to_string_lossy();
    let bin_path = tmp.join(stem.as_ref());

    let result = Command::new(BRUST)
        .args([path_str, "-o", bin_path.to_str().unwrap()])
        .output()
        .unwrap_or_else(|e| panic!("failed to spawn brust: {e}"));

    match expect {
        Expect::Error(patterns) => {
            // Must fail to compile.
            if result.status.success() {
                panic!("expected compilation to fail, but brust succeeded");
            }
            let stderr = String::from_utf8_lossy(&result.stderr);
            for pat in &patterns {
                if !stderr.contains(pat.as_str()) {
                    panic!("stderr missing pattern {:?}\nstderr:\n{}", pat, stderr.trim());
                }
            }
        }
        Expect::Success(expected_lines) => {
            // Must compile successfully.
            if !result.status.success() {
                panic!(
                    "brust error:\n{}",
                    String::from_utf8_lossy(&result.stderr).trim()
                );
            }
            // Run the compiled binary.
            let run = Command::new(&bin_path)
                .output()
                .unwrap_or_else(|e| panic!("failed to run binary: {e}"));

            let stdout = String::from_utf8_lossy(&run.stdout);
            let actual: Vec<&str> = stdout.lines().collect();
            let expected: Vec<&str> = expected_lines.iter().map(String::as_str).collect();

            if actual != expected {
                let exp = if expected_lines.is_empty() {
                    "<empty>".to_string()
                } else {
                    expected_lines.join("\n")
                };
                let act = if actual.is_empty() {
                    "<empty>".to_string()
                } else {
                    actual.join("\n")
                };
                panic!("stdout mismatch\nexpected:\n{exp}\nactual:\n{act}");
            }
        }
    }
}

/// Parse the leading comment block of a test file.
/// Lines starting with `// out:` define expected stdout (success test).
/// Lines starting with `// err:` define expected stderr substrings (error test).
/// Stops at the first non-comment line.
fn parse_header(src: &str) -> Expect {
    let mut out_lines: Vec<String> = Vec::new();
    let mut err_patterns: Vec<String> = Vec::new();

    for line in src.lines().take_while(|l| l.starts_with("//")) {
        if let Some(rest) = line.strip_prefix("// out: ") {
            out_lines.push(rest.to_string());
        } else if line == "// out:" {
            out_lines.push(String::new());
        } else if let Some(rest) = line.strip_prefix("// err: ") {
            err_patterns.push(rest.to_string());
        }
    }

    if !err_patterns.is_empty() {
        Expect::Error(err_patterns)
    } else {
        Expect::Success(out_lines)
    }
}

// One #[test] fn per .rs file, generated by build.rs at compile time.
include!(concat!(env!("OUT_DIR"), "/suite_tests.rs"));
