//! Integration tests for the brust compiler.
//!
//! Each `.rs` file in `tests/suite/` is compiled to a native binary by the
//! brust binary (which internally generates C and invokes `$CC`). Its stdout
//! is compared against the `// out: <line>` comments at the top of the file.
//!
//! Each test file gets its own `#[test]` function (generated by build.rs), so
//! cargo runs them all in parallel and reports failures individually.

use std::{fs, path::Path, process::Command};

// Resolved at compile time by cargo.
const BRUST: &str = env!("CARGO_BIN_EXE_brust");

/// Run a single `.rs` file through the full compile-and-execute pipeline.
/// Panics with a descriptive message on any failure.
fn run_test(br_path: &str) {
    let path = Path::new(br_path);
    let src = fs::read_to_string(path).unwrap_or_else(|e| panic!("cannot read {br_path}: {e}"));
    let expected = parse_expected(&src);

    let tmp = std::env::temp_dir().join("brust_test_suite");
    fs::create_dir_all(&tmp).expect("cannot create temp dir");

    let stem = path.file_stem().unwrap().to_string_lossy();
    let bin_path = tmp.join(stem.as_ref());

    // Compile .rs -> binary (brust invokes cc internally)
    let out = Command::new(BRUST)
        .args([br_path, "-o", bin_path.to_str().unwrap()])
        .output()
        .unwrap_or_else(|e| panic!("failed to spawn brust: {e}"));
    if !out.status.success() {
        panic!(
            "brust error:\n{}",
            String::from_utf8_lossy(&out.stderr).trim()
        );
    }

    // Run the compiled binary
    let out = Command::new(&bin_path)
        .output()
        .unwrap_or_else(|e| panic!("failed to run binary: {e}"));

    let stdout = String::from_utf8_lossy(&out.stdout);
    let actual: Vec<&str> = stdout.lines().collect();
    let expected_refs: Vec<&str> = expected.iter().map(String::as_str).collect();

    if actual != expected_refs {
        let exp = if expected.is_empty() {
            "<empty>".to_string()
        } else {
            expected.join("\n")
        };
        let act = if actual.is_empty() {
            "<empty>".to_string()
        } else {
            actual.join("\n")
        };
        panic!("stdout mismatch\nexpected:\n{exp}\nactual:\n{act}");
    }
}

/// Extract expected output lines from leading `// out: <line>` comments.
/// `// out:` (with no trailing text) represents an empty output line.
/// Stops at the first non-comment line.
fn parse_expected(src: &str) -> Vec<String> {
    src.lines()
        .take_while(|l| l.starts_with("//"))
        .filter_map(|l| {
            if let Some(rest) = l.strip_prefix("// out: ") {
                Some(rest.to_string())
            } else if l == "// out:" {
                Some(String::new())
            } else {
                None
            }
        })
        .collect()
}

// One #[test] fn per .rs file, generated by build.rs at compile time.
include!(concat!(env!("OUT_DIR"), "/suite_tests.rs"));
